#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May 10 11:14:37 2018

@author: miri-o
"""


import pandas as pd
import biovec
import time
from tqdm import tqdm
import numpy as np

path = '/media/miri-o/Documents/'
Celiac_model = biovec.models.load_protvec(path+'trained_models/CDR3_model_Celiac_based_20180506.txt')
infile = pd.read_csv(path+'CDR3_from_Celiac_full.csv2018-05-10-1226', sep='\t')

# =============================================================================
# samples = infile.SAMPLE.unique()
# for i in tqdm(range(len(samples))):
#     time.sleep(3)
# =============================================================================
n = len(infile)
randvectors_word2vec = np.zeros((n,100))
to_drop = []
index = 0
for i in tqdm(range(n)):
    word = infile['JUNC_AA'].iloc[i]
    randvectors_word2vec[i] = list(Celiac_model.to_vecs(word)[0])

#np.savetxt(path+'Celiac_vectors_2969380x100', randvectors_word2vec, delimiter=',')    

df = pd.DataFrame(randvectors_word2vec)
df.to_csv(path+'Celiac_vectors_2969380x100.csv', index= False)